version: "3"

services:
  web:
    container_name: web
    build:
      context: ./koak_webapp
    environment:
      REACT_APP_DEV_ENV: "TRUE"
    image: web
    ports:
      - 8081:8081
    expose:
      - 8081
    stdin_open: true
    volumes:
      - apk:/mobile_app/
    depends_on:
      - mobile

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 8080:8080
    expose:
      - 8080
    stdin_open: true
    restart: always

  mobile:
    container_name: mobile
    build:
      context: ./koak_mobileapp
    volumes:
      - apk:/mobile_app/

volumes:
  apk:
  mongo_data: